### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eXeC64** [mustrumr/slimacme#1]
This project looks nice, but before anyone can really use it, some documentation is needed. Could you document how it should be used with the Lets Encrypt CA?

**Comment by mustrumr** [comment]
It's a work-in-progress and I currently don't have much time. I will submit examples when I update it to the current ACME draft (hopefully this week).

**Comment by mustrumr** [comment]
There's an example now.

**Comment by eXeC64** [comment]
:+1:
